IGEN/Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace IGEN.Models
{
    public class Game
    {
        /*Basic game info class used in article pages (on the right hand side of article text). ICollection used to connect games to articles.*/
        public int ID { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string CoverArt { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string Developer { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
    }
}

IGEN/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IGEN.Models;

namespace IGEN.Controllers
{
    [Authorize(Roles = "Creator, Admin")]
    public class GamesController : Controller
    {
        private ContentDbContext db = new ContentDbContext();

        // GET: Games
        public ActionResult Index()
        {
            return View(db.Game.ToList());
        }

        // GET: Games/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CoverArt,Title,Developer")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Game.Add(game);
                db.SaveChanges();
                return RedirectToAction("Create", "Articles");
            }

            return View(game);
        }

        // GET: Games/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CoverArt,Title,Developer")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(game);
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Game game = db.Game.Find(id);
            db.Game.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IGEN/Controllers/HomeEditsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using IGEN.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace IGEN.Controllers
{
    public class HomeEditsController : Controller
    {
        private ContentDbContext db = new ContentDbContext();

        // GET: HomeEdits
        public ActionResult Index()
        {
            bool gameExists = db.Game.Any(game => game.ID == game.ID);
            bool articleExists = db.Article.Any(article => article.ID == article.ID);
            bool homeExists = db.HomeEdit.Any(home => home.ID == home.ID);

            /*The following creates a sample article first time starting the project, otherwise it will give an error since much of the content on the startpage depends on there actually existing articles (should be atleast 8 for most read part to show properly)*/
            if (!gameExists)
            {
                Game newgame = new Game();
                newgame.ID = 1;
                newgame.Title = "Sample";
                newgame.CoverArt = "http://www.mobygames.com/images/covers/l/367150-battlefield-1-windows-front-cover.png";
                newgame.Developer = "Sample";
                db.Game.Add(newgame);
                db.SaveChanges();
            }
            if (!articleExists)
            {
                Article newarticle = new Article();
                newarticle.ID = 1;
                newarticle.Header = "Sample";
                newarticle.BigPic = "https://cdn.mos.cms.futurecdn.net/eZ6pqBFQtymNTiksWQCJWo-650-80.jpg";
                newarticle.Date = DateTime.Now;
                newarticle.Author = "Sample";
                newarticle.Text = "Lorem ipsum.";
                newarticle.GameID = 1;
                newarticle.IsLocked = false;
                db.Article.Add(newarticle);
                db.SaveChanges();
            }
            if (!homeExists)
            {
                HomeEdit newhome = new HomeEdit();
                newhome.ID = 1;
                newhome.FrontPicID = 1;
                newhome.CardPic1ID = 1;
                newhome.CardPic2ID = 1;
                newhome.CardPic3ID = 1;
                newhome.CardPic4ID = 1;
                newhome.CardPic5ID = 1;
                newhome.CardPic6ID = 1;
                db.HomeEdit.Add(newhome);
                db.SaveChanges();
            }
            var homeEdit = db.HomeEdit.Include(h => h.CardPic1).Include(h => h.CardPic2).Include(h => h.CardPic3).Include(h => h.CardPic4).Include(h => h.CardPic5).Include(h => h.CardPic6).Include(h => h.FrontPic);
            return View(homeEdit.ToList());
        }

        [Authorize(Roles = "Admin")]
        // GET: HomeEdits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeEdit homeEdit = db.HomeEdit.Find(id);
            if (homeEdit == null)
            {
                return HttpNotFound();
            }
            return View(homeEdit);
        }

        [Authorize(Roles = "Admin")]
        // GET: HomeEdits/Create
        public ActionResult Create()
        {
            ViewBag.CardPic1ID = new SelectList(db.Article, "ID", "Header");
            ViewBag.CardPic2ID = new SelectList(db.Article, "ID", "Header");
            ViewBag.CardPic3ID = new SelectList(db.Article, "ID", "Header");
            ViewBag.CardPic4ID = new SelectList(db.Article, "ID", "Header");
            ViewBag.CardPic5ID = new SelectList(db.Article, "ID", "Header");
            ViewBag.CardPic6ID = new SelectList(db.Article, "ID", "Header");
            ViewBag.FrontPicID = new SelectList(db.Article, "ID", "Header");
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: HomeEdits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FrontPicID,CardPic1ID,CardPic2ID,CardPic3ID,CardPic4ID,CardPic5ID,CardPic6ID")] HomeEdit homeEdit)
        {
            if (ModelState.IsValid)
            {
                db.HomeEdit.Add(homeEdit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CardPic1ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic1ID);
            ViewBag.CardPic2ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic2ID);
            ViewBag.CardPic3ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic3ID);
            ViewBag.CardPic4ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic4ID);
            ViewBag.CardPic5ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic5ID);
            ViewBag.CardPic6ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic6ID);
            ViewBag.FrontPicID = new SelectList(db.Article, "ID", "Header", homeEdit.FrontPicID);
            return View(homeEdit);
        }

        [Authorize(Roles = "Admin")]
        // GET: HomeEdits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeEdit homeEdit = db.HomeEdit.Find(id);
            if (homeEdit == null)
            {
                return HttpNotFound();
            }
            ViewBag.CardPic1ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic1ID);
            ViewBag.CardPic2ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic2ID);
            ViewBag.CardPic3ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic3ID);
            ViewBag.CardPic4ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic4ID);
            ViewBag.CardPic5ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic5ID);
            ViewBag.CardPic6ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic6ID);
            ViewBag.FrontPicID = new SelectList(db.Article, "ID", "Header", homeEdit.FrontPicID);
            return View(homeEdit);
        }

        [Authorize(Roles = "Admin")]
        // POST: HomeEdits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FrontPicID,CardPic1ID,CardPic2ID,CardPic3ID,CardPic4ID,CardPic5ID,CardPic6ID")] HomeEdit homeEdit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(homeEdit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CardPic1ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic1ID);
            ViewBag.CardPic2ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic2ID);
            ViewBag.CardPic3ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic3ID);
            ViewBag.CardPic4ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic4ID);
            ViewBag.CardPic5ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic5ID);
            ViewBag.CardPic6ID = new SelectList(db.Article, "ID", "Header", homeEdit.CardPic6ID);
            ViewBag.FrontPicID = new SelectList(db.Article, "ID", "Header", homeEdit.FrontPicID);
            return View(homeEdit);
        }

        [Authorize(Roles = "Admin")]
        // GET: HomeEdits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HomeEdit homeEdit = db.HomeEdit.Find(id);
            if (homeEdit == null)
            {
                return HttpNotFound();
            }
            return View(homeEdit);
        }

        [Authorize(Roles = "Admin")]
        // POST: HomeEdits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HomeEdit homeEdit = db.HomeEdit.Find(id);
            db.HomeEdit.Remove(homeEdit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public PartialViewResult JustPosted()
        {
            int maxID = db.Article.Max(p => p.ID);
            ViewData["LatestArticle"] = maxID;
            /*Following sends the article db for use in the partial view. Must use partial view to use both HomeEdit and Article models for the startpage (but only Article is used here).*/
            var justPosted = db.Article;
            return PartialView("JustPosted", justPosted.ToList());
        }

        public PartialViewResult MostRead()
        {
            /*Same as above.*/
            var mostRead = db.Article;
            return PartialView("MostRead", mostRead.ToList());
        }

        public ActionResult Magazine()
        {
            return View();
        }

        public ActionResult Subscribe(bool? loggedin)
        {
            /*Used so subscribed users aren't able to subscribe again.*/
            if (User.IsInRole("Subscriber") || User.IsInRole("Admin") || User.IsInRole("Creator"))
            {

IGEN/Views/Games/Create.cshtml
@model IGEN.Models.Game

@{
    ViewBag.Title = "| Create game";
}

<h2 id="topcreate">Create game</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <hr id="createtophr"/>
    @Html.ValidationSummary(true, "")
    @Html.LabelFor(model => model.CoverArt, new { id = "create-header-label", @class = "create-header-label-game" })
    @Html.EditorFor(model => model.CoverArt, new { htmlAttributes = new { placeholder = "Must be LINK to picture. Preferred standard cover art image.", id = "create-header" } })
    @Html.ValidationMessageFor(model => model.CoverArt, "", new { id = "create-header-val" })
    <br/>
    @Html.LabelFor(model => model.Title, new { id = "create-bigpic-label", @class = "create-bigpic-label-game" })
    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { id = "create-bigpic" } })
    @Html.ValidationMessageFor(model => model.Title, "", new { id = "create-bigpic-val" })
    <br/>
    @Html.LabelFor(model => model.Developer, new { id = "create-date-label", @class = "create-date-label-game" })
    @Html.EditorFor(model => model.Developer, new { htmlAttributes = new { id = "create-date" } })
    @Html.ValidationMessageFor(model => model.Developer, "", new { id = "create-date-val" })
    <br/>
    <input id="submit" class="submit-create submit-create-game" type="submit" value="Create" />
}

<hr id="articlehr-login">
<div id="socialmedia-login">
    <p>Visit us on social media</p>
    <a id="spa1-login" href="https://facebook.com"><img src="@Url.Content("~/Content/images/facebook.png")" alt="facebook" /></a>
    <a id="spa2-login" href="https://twitter.com"><img src="@Url.Content("~/Content/images/twitter.png")" alt="twitter" /></a>
    <a id="spa3-login" href="https://instagram.com"><img src="@Url.Content("~/Content/images/instagram.png")" alt="instagram" /></a>
    <a id="spa4-login" href="https://youtube.com"><img src="@Url.Content("~/Content/images/youtube.png")" alt="youtube" /></a>
</div>
<div id="footer-login">
    <img id="footerlogo" src="@Url.Content("~/Content/images/IGEN_red_text.png")" alt="logo" />
    <p id="fp1"><a href="@Url.Action("Index", "HomeEdits")">Home</a> <span class="whitedot">•</span> <a href="tos.html">Terms of Use</a> <span class="whitedot">•</span> <a href="@Url.Action("Contact", "HomeEdits")">Contact Us</a></p>
    <p id="fp2"><a href="@Url.Action("About", "HomeEdits")">About Us</a> <span class="whitedot">•</span> <a href="copyright.html">Copyright</a> <span class="whitedot">•</span> <a href="tip.html">Tip Us</a></p>
    <p id="fp3">© 2018 - Ingenious Gamer & Electronics News</p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IGEN/Views/Games/Delete.cshtml
@model IGEN.Models.Game

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CoverArt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoverArt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Developer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Developer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IGEN/Views/Games/Details.cshtml
@model IGEN.Models.Game

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CoverArt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoverArt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Developer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Developer)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IGEN/Views/Games/Edit.cshtml
@model IGEN.Models.Game

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Game</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CoverArt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoverArt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoverArt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Developer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Developer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Developer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IGEN/Views/Games/Index.cshtml
@model IEnumerable<IGEN.Models.Game>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CoverArt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Developer)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CoverArt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Developer)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>